version: 2

models:
  - name: stg_seed_sample_data
    description: This is the sample source data staged in our dbt_project. We add a row_number at this stage as we know it will be useful for later when we need to write a query to create a mapping table to rename the old_headers to the new ones. The other thing to note about this sample data is why it is appropriate for use in the tool. This spreadsheet has nested headers where header information is in the first data row. We want to concatenate this supplementary info with the primary header value (which will likely need to be copied down across rows) to get a complete header value.

    columns:
      - name: employee
        description: This is observation data so this field states which employee is being observed

      - name: Observation_Start_Time
        description: when observation started

      - name: Observation_Interval
        description: which of multiple observations is this referring to

      - name: Observation_Length_mins
        description: how long the singular observation was for

      - name: Interaction_With
        description: this is an example of a nested header the next 4 columns have empty header values and are therefore assigned a single letter as a placeholder. Meanwhile in the first data row is a value for who the employee was interacting with. It would make sense to update these headers to Interaction_With_Manager or Interaction_With_Coworker etc.

  - name: int_seed_data_only_table
    description: This is an intermediate table with the first row filtered out so that the data in this table is purely that data. This then serves as a good table to use as the one that can have its headers renamed - after that it will be the kind of table that is ready to be transformed into a state that can be analysed.

  - name: int_seed_header_mapping
    description: This table is the product of a query that returns a table with a row for every column from the input data with the first column being the new column headers and the second column being the original column headers for the table. We also use the query to remove any special characters in data_row1 that could cause issues as a sql column header.

    columns:
      - name: new_header
        description: the value that the original header should be changed to

      - name: header
        description: the value that the header is upon initial reading.
